name: daniel_ui_template_lib
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.0
  photo_view: ^0.15.0
  flutter_svg: ^2.0.7
  any_link_preview: ^3.0.0
  riverpod_clean_architecture_lib:
    git:
      url: https://github.com/donghyun-Kim0405/riverpod_clean_architecture_lib.git
      ref: v1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
